[build-system]
requires = ['setuptools>=42']
build-backend = 'setuptools.build_meta'

[project]
name = "locations"
version = "1.1.1"
authors = [
  { name="Ashish Mishra", email="ashishmishra.dev04@gmail.com" },
]
description = "This library will be used to extract usa location"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Coderboy004/locations"
"Bug Tracker" = "https://github.com/Coderboy004/locations/issues"